module.exports = [
{ id : "1", fact: "Unlike Mr. T, Chuck Norris doesn't pity the fool. He roundhouse kicks him." },
{ id : "2", fact: "Chuck Norris writes only in the first person because that's the only person that matters to anyone." },
{ id : "3", fact: "Chuck Norris can eat a rubix cube and crap it out solved." },
{ id : "4", fact: "Chuck Norris and Superman once fought each other on a bet. The loser had to start wearing his underwear on the outside of his pants." },
{ id : "5", fact: "Chuck Norris wears a cup not to protect himself, but to protect the players on the other team." },
{ id : "6", fact: "Chuck Norris took Mother Nature from behind. We refer to the event as the Big Bang." },
{ id : "7", fact: "Leading hand sanitizers claim they can kill 99.9 percent of germs. Chuck Norris can kill 100 percent of whatever the fuck he wants." },
{ id : "8", fact: "Chuck Norris came before the chicken and the egg." },
{ id : "9", fact: "Chuck Norris cannot predict the future; the future just better fucking do what Chuck Norris says." },
{ id : "10", fact: "Chuck Norris doesn't play 'hide- and-seek.' He plays 'hide-and- pray-I-don't-find-you.'" },
{ id : "11", fact: "Chuck Norris once had an erection while lying face down and struck oil." },
{ id : "12", fact: "Chuck Norris is currently in a legal battle with the makers of Bubble Tape. Norris claims '6 Feet of Fun' is actually the trademark for his penis." },
{ id : "13", fact: "Chuck Norris doesn't use pickup lines, he simply says, 'Now.'" },
{ id : "14", fact: "Chuck Norris has Chuck Norris Quotes on his website" },
{ id : "15", fact: "Chuck Norris doesn't need a miracle in order to split the ocean. He just walks in and the water gets the fuck out of the way." },
{ id : "16", fact: "Jack was nimble, Jack was quick, but Jack still couldn't dodge Chuck Norris' roundhouse kick." },
{ id : "17", fact: "In fine print on the last page of the Guinness Book of World Records it notes that all world records are held by Chuck Norris, and those listed in the book are simply the closest anyone else has ever gotten." },
{ id : "18", fact: "Crop circles are Chuck Norris' way of telling the world that sometimes corn needs to lie the fuck down." },
{ id : "19", fact: "Chuck Norris is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing." },
{ id : "20", fact: "Chuck Norris is a man of few words. Chuck Norris is not a man of few roundhouse kicks to the face." },
{ id : "21", fact: "Chuck Norris once had a heart attack; his heart lost." },
{ id : "22", fact: "When Chuck Norris enters a room, he doesn't turn the lights on, he turns the dark off." },
{ id : "23", fact: "Chuck Norris can build a snowman out of rain." },
{ id : "24", fact: "Chuck Norris has to maintain a concealed weapon license in all 50 states in order to legally wear pants." },
{ id : "25", fact: "Death once had a near-Chuck-Norris experience." },
{ id : "26", fact: "The Four Horsemen of the Apocalypse actually live in Chuck Norris's nutsack." },
{ id : "27", fact: "Chuck Norris doesn't pop his collar, his shirts just get erections when they touch his body." },
{ id : "28", fact: "When observing a Chuck Norris roundhouse kick in slow motion one finds that Chuck Norris actually rapes his victim in the ass, smokes a cigarette with Dennis Leary, and then roundhouse kicks them in the face." },
{ id : "29", fact: "Chuck Norris doesn't have hair on his testicles, because hair does not grow on steel." },
{ id : "30", fact: "Rudolph has a red nose because he got lippy and Chuck Norris roundhouse kicked him across the face several times." },
{ id : "31", fact: "Chuck Norris' dog is trained to pick up his own poop because Chuck Norris will not take shit from anyone." },
{ id : "32", fact: "Chuck Norris once tried to wear glasses. The result was him seeing around the world to the point where he was looking at the back of his own head. " },
{ id : "33", fact: "Pee Wee Herman got arrested for masturbating in public. The same day, Chuck Norris got an award for masturbating in public. " },
{ id : "34", fact: "Once a grizzly bear threatened to eat Chuck Norris. Chuck showed the bear his fist and the bear proceeded to eat himself, because it would be the less painful way to die. " },
{ id : "35", fact: "If Chuck Norris is late, time better slow the fuck down. " },
{ id : "36", fact: "Chuck Norris sleeps with a night light. Not because Chuck Norris is afraid of the dark, but the dark is afraid of Chuck Norris. " },
{ id : "37", fact: "Chuck Norris can touch MC Hammer. " },
{ id : "38", fact: "Chuck Norris ordered a Big Mac at Burger King, and got one. " },
{ id : "39", fact: "Chuck Norris always has sex on the first date. Always. " },
{ id : "40", fact: "A Handicap parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there. " },
{ id : "41", fact: "Chuck Norris frequently donates blood to the Red Cross. Just never his own." },
{ id : "42", fact: "Some people piss their name in the snow. Chuck Norris can piss his name into concrete." },
{ id : "43", fact: "Chuck Norris once visited the Virgin Islands. They are now The Islands." },
{ id : "44", fact: "Chuck Norris can speak braille." },
{ id : "45", fact: "When asked what type of vehicle he drives, Chuck Norris responded slyly with 'Don't you mean what kind of vehicle drives me?'" },
{ id : "46", fact: "Chuck Norris' evil twin brother, Richard Simmons, once approached Chuck with the hope of reconciliation, but at the sight of Richard's curly, well kept hair, Chuck Norris became so enraged that he turned green with hate and ripped Richard Simmons arms and legs off. This action was the origin of the Marvel Comic badass, The Incredibl Hulk." },
{ id : "47", fact: "Industrial logging isn't the cause of deforestation. Chuck Norris needs toothpicks." },
{ id : "48", fact: "Chuck Norris doesn't worry about changing his clock twice a year for daylight savings time. The sun rises and sets when Chuck tells it to." },
{ id : "49", fact: "There are three legal methods of execution in the United States: lethal injection, gas chamber, and Chuck Norris." },
{ id : "50", fact: "If paper beats rock, rock beats scissors, and scissors beats paper, what beats all 3 at the same time? Answer: Chuck Norris." },
{ id : "51", fact: "Chuck Norris enjoys a good practical joke. His favorite is where he removes your lower intestine and pretends to make a balloon animal out of it. Then he cracks your skull open with a Volvo for not complimenting him on his balloon animal." },
{ id : "52", fact: "Chuck Norris ’ roundhouse kick is so powerful, it can be seen from outer space by the naked eye." },
{ id : "53", fact: "If you want a list of Chuck Norris’ enemies, just check the extinct species list." },
{ id : "54", fact: "There is no theory of evolution just a list of creatures Chuck Norris allows to live." },
{ id : "55", fact: "Nine out of ten scientists agree that Chuck Norris, not the Big Bang, created the universe. The tenth scientist has never been found." },
{ id : "56", fact: "Chuck Norris eats transformer toys in vehicle mode and poos them out transformed into a robot." },
{ id : "57", fact: "CNN was originally created as the 'Chuck Norris Network' to update Americans with on-the-spot ass kicking in real-time." },
{ id : "58", fact: "A blind man once stepped on Chuck Norris' shoe. Chuck replied, 'Don't you know who I am? I'm Chuck Norris!' The mere mention of his name cured this man blindness. Sadly the first, last, and only thing this man ever saw, was a fatal roundhouse delivered by Chuck Norris." },
{ id : "59", fact: "Chuck Norris has already been to Mars; that's why there are no signs of life there." },
{ id : "60", fact: "The Seven Wonders of the ancient world were: Chuck Norris' left and right hands, his left and right feet, his belly button, his liver, and his beard." },
{ id : "61", fact: "TNT was originally developed by Chuck Norris to cure indigestion." },
{ id : "62", fact: "Chuck Norris ate a 10 pound steak in an hour. He spent the first 55 minutes banging the waitress." },
{ id : "63", fact: "Chuck Norris built a time machine and went back in time to stop the JFK assassination. As Oswald shot, Chuck Norris met all three bullets with his beard, deflecting them. JFK's head exploded out of sheer amazement." },
{ id : "64", fact: "Ironically, Chuck Norris ’ hidden talent is invisibility." },
{ id : "65", fact: "Once a cobra bit Chuck Norris' leg. After five days of excruciating pain, the cobra died." },
{ id : "66", fact: "If at first you don't succeed, you're not Chuck Norris." },
{ id : "67", fact: "Chuck Norris owns the greatest poker face of all-time. It helped him win the 1983 world series of poker despite him holding just a joker, a 2 of clubs, a 7 of spades, and a green number 4 from Uno and a monopoly ‘get out of jail free’ card." },
{ id : "68", fact: "The leading causes of the death in the United States: 1. Heart attack 2. Chuck Norris 3. Cancer" },
{ id : "69", fact: "Chuck Norris invented a language that incorporates karate and roundhouse kicks. So next time Chuck Norris is kicking your ass, don’t be offended or hurt, he may be just trying to tell you he likes your hat." },
{ id : "70", fact: "One time while sparring with Wolverine, Chuck Norris accidentally lost his left testicle. You might be familiar with it to this very day by its technical term: Jupiter." },
{ id : "71", fact: "Chuck Norris can strangle you with a cordless phone." },
{ id : "72", fact: "The real reason Hitler killed himself is because he found out that Chuck Norris is Jewish." },
{ id : "73", fact: "Chuck Norris is the reason Waldo is hiding." },
{ id : "74", fact: "Chuck Norris puts the 'laughter' in 'manslaughter'." },
{ id : "75", fact: "The saddest moment for a child is not when he learns Santa Claus isn't real, it's when he learns Chuck Norris is. " },
{ id : "76", fact: "If you swallow a quarter and Chuck Norris round house kicks you in the stomach you will crap out two dimes and a nickel." },
{ id : "77", fact: "Chuck Norris can kill two stones with one bird." },
{ id : "78", fact: "Giraffes were created when Chuck Norris uppercutted a horse." },
{ id : "79", fact: "Chuck Norris' calendar goes straight from March 31st to April 2nd. No one fools Chuck Norris." },
{ id : "80", fact: "Brett Favre can throw a football over 50 yards. Chuck Norris can throw Brett Favre even further." },
{ id : "81", fact: "Chuck Norris sleeps with a pillow under his gun." },
{ id : "82", fact: "Chuck Norris knows Victoria's secret." },
{ id : "83", fact: "Chuck Norris used to beat the shit out of his shadow because it was following to close. It now stands a safe 30 feet behind him." },
{ id : "84", fact: "A bulletproof vest wears Chuck Norris for protection." },
{ id : "85", fact: "Chuck Norris doesn't chec death. He wins fair and square." },
{ id : "86", fact: "Jesus can walk on water, but Chuck Norris can swim through dry land." },
{ id : "87", fact: "Chuck actually died four years ago, but the Grim Reaper can't get up the courage to tell him." },
{ id : "88", fact: "Chuck Norris's computer has no 'backspace' button, Chuck Norris doesn't make mistakes." },
{ id : "89", fact: "Chuck Norris once heard that nothing can kill him, so he tracked down nothing and killed it." },
{ id : "90", fact: "The reason the Holy Grail has never been recovered is because nobody is brave enough to ask Chuck Norris to give up his favourite coffee mug." },
{ id : "91", fact: "Chuck Norris was once on Celebrity Wheel of Fortune and was the first to spin. The next 29 minutes of the show consisted of everyone standing around awkwardly, waiting for the wheel to stop." },
{ id : "92", fact: "Champions eat wheaties for breakfast. Chuck Norris eats champions for breakfast." },
{ id : "93", fact: "The opening scene of the movie 'Saving Private Ryan' is loosely based on games of dodgeball Chuck Norris played in second grade." },
{ id : "94", fact: "Chuck Norris' tears cure cancer. Too bad he has never cried." },
{ id : "95", fact: "Chuck Norris counted to infinity twice." },
{ id : "96", fact: "When Chuck Norris swims, he doesn’t get wet. The water gets Chuck Norris." },
{ id : "97", fact: "Chuck Norris sold his soul to the devil for his rugged good looks and unparalleled martial arts ability. Shortly after the transaction was finalized, Chuck roundhouse kicked the devil in the face and took his soul back. The devil, who appreciates irony, couldn't stay mad and admitted he should have seen it coming. They now play poker every second Wednesday of the month." },
{ id : "98", fact: "When an episode of Walker Texas Ranger was aired in France, the French surrendered to Chuck Norris just to be on the safe side." },
{ id : "99", fact: "Chuck Norris doesn't read books. He stares them down until he gets the information he wants." },
{ id : "100", fact: "Chuck Norris does not sleep. He waits." },
{ id : "101", fact: "Chuck Norris lost his virginity before his dad did."},
{ id : "102", fact: "All Chuck Norris facts are scientifically proven."}];
